# Generated by Django 4.0.4 on 2022-07-11 04:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSclient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.CharField(max_length=50, verbose_name='Clients Full Name')),
                ('clientsemail', models.EmailField(max_length=254, verbose_name='Clients Email')),
                ('address', models.TextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='User Phone Number')),
                ('payment', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('MOBILE', 'MOBILE')], default='CASH', max_length=50)),
                ('provider', models.CharField(blank=True, max_length=50, null=True, verbose_name='Service Provider')),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresss',
            },
        ),
        migrations.CreateModel(
            name='POSorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SlugField(editable=False, unique=True, verbose_name='order')),
            ],
        ),
        migrations.CreateModel(
            name='POSproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=160, verbose_name='Product Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='slug')),
                ('coverImage', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, size=[300, 350], upload_to='product/cover/%Y/%m/%d', verbose_name='cover Image')),
                ('descripton', models.TextField(verbose_name='Product description')),
                ('sku', models.CharField(max_length=50, verbose_name='Stock Keeping Unit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='normal Price')),
                ('wholeSalePrice', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='wholesale Price')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Approved for POS')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.brand', verbose_name='brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.prouctcategory', verbose_name='category')),
            ],
        ),
    ]
