# Generated by Django 4.0.4 on 2022-07-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posclient',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
