# Generated by Django 4.0.4 on 2022-07-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0002_posclient_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posclient',
            name='active',
        ),
        migrations.AddField(
            model_name='posclient',
            name='isactive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
