# Generated by Django 4.0.4 on 2022-07-04 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='owner',
        ),
    ]
