# Generated by Django 4.0.4 on 2022-07-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_active_order_paid_at_order_promo_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
