# Generated by Django 4.0.4 on 2022-06-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_favouriteproduct_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouriteproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Favourite', 'verbose_name_plural': 'Favourites'},
        ),
    ]
