# Generated by Django 4.0.4 on 2022-06-02 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerOrRetailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=160, verbose_name='Business Name')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Business Phone Number')),
                ('address', models.TextField(verbose_name='Business Address')),
                ('businessLincese', models.FileField(blank=True, help_text='Upload Business Lincence', null=True, upload_to='', verbose_name='Bussiness Lincence')),
                ('businessType', models.CharField(choices=[('Registered', 'Registered'), ('Not Registered', 'Not Registered')], max_length=60, verbose_name='Business Type')),
                ('tin', models.FileField(blank=True, help_text='Upload Tax Indentification', null=True, upload_to='', verbose_name='Tax Indentification')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductManufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=160, verbose_name='Manufacture Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='slug')),
                ('relationship', models.CharField(choices=[('Junior Employee', 'Junior Employee'), ('Senior Employee', 'Senior Employee'), ('Approved Representative', 'Approved Representative'), ('Owner', 'Owner')], default='Junior Employee', max_length=50, verbose_name='Relationship to Business')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Business Phone Number')),
                ('address', models.TextField(verbose_name='Business Address')),
                ('businessType', models.CharField(choices=[('Registered', 'Registered'), ('Not Registered', 'Not Registered')], max_length=60, verbose_name='Business Type')),
                ('businessLincese', models.FileField(blank=True, help_text='Upload Business Lincence', null=True, upload_to='upload/businesslicense/', verbose_name='Bussiness Lincence')),
                ('tin', models.FileField(blank=True, help_text='Upload Tax Indentification', null=True, upload_to='upload/tin/', verbose_name='Tax Indentification')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
