# Generated by Django 4.0.4 on 2022-06-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounttype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmanufacture',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resellerorretailer',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
