# Generated by Django 4.0.4 on 2022-07-11 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounttype', '0002_alter_team_company_alter_teammembers_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='accounttype.team'),
        ),
    ]
