# Generated by Django 4.0.4 on 2022-06-02 16:34

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coverImage',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, size=[200, 400], upload_to='product/cover/%Y/%m/%d', verbose_name='cover Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, size=[800, 900], upload_to='product/images/%Y/%m/%d', verbose_name='Other Product Images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product'),
        ),
    ]
