# Generated by Django 4.0.4 on 2022-06-19 21:36

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_coverimage_alter_productimage_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coverImage',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, size=[300, 350], upload_to='product/cover/%Y/%m/%d', verbose_name='cover Image'),
        ),
    ]
