# Generated by Django 4.0.4 on 2022-06-02 13:02

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounttype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=160, verbose_name='Brand Name')),
                ('slug', models.SlugField(editable=False, null=True, unique=True, verbose_name='slug')),
                ('brandlogo', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, size=[100, 100], upload_to='uploads/brands')),
                ('description', models.TextField(verbose_name='Brand Description')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounttype.productmanufacture', verbose_name='Product Manufacture')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
    ]
