# Generated by Django 4.0.4 on 2022-06-02 13:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_brand_brandlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brandlogo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, size=[100, 100], upload_to='uploads/brands'),
        ),
    ]
